# config.yaml
# make (and params) these conditional on component config dictionary
# These configurations should appear logged in a more 'global' log --
# eg. when the aggregator 'starts' and only once -- no need to pollute
# the data stream with repetitive configuration info.



[ADXL345]
adxl345_TAP_ENABLED = True
adxl345_TAP_COUNT = 1
adxl345_TAP_THRESHOLD = 20
adxl345_TAP_DURATION = 50
adxl345_TAP_LATENCY = 30
adxl345_TAP_WINDOW = 255

adxl345_DROP_ENABLED = False
adxl345_DROP_THRESHOLD = 10
adxl345_DROP_TIME = 25

adxl345_MOTION_ENABLED = False
adxl345_MOTION_THRESHOLD = 18

adxl345_DATARATE = adafruit_adxl34x.DataRate.RATE_100_HZ
adxl345_RANGE = adafruit_adxl34x.Range.RANGE_2_G

[ADS1015]
ads_C0_ENABLED = True
ads_C1_ENABLED = True
ads_C2_ENABLED = True
ads_C3_ENABLED = True

[BNO055]
bno055_MODE = adafruit_bno055.NDOF_MODE

# Switches the use of external crystal on or off.
bno055_EXTERNAL_CRYSTAL = True
# Switches the use of external crystal on or off.
bno055_USE_EXTERNAL_CRYSTAL = True

bno055_ACCELERATION_ENABLED = True
bno055_ACCELERATION_ACCEL_BANDWIDTH =
# Switch the accelerometer bandwidth and return the new bandwidth. Default value: 62.5 Hz See table 3-8 in the datasheet.
bno055_ACCELERATION_ACCEL_MODE =
# Switch the accelerometer mode and return the new mode. Default value: Normal See table 3-8 in the datasheet.
bno055_ACCELERATION_ACCEL_RANGE =
# Switch the accelerometer range and return the new range. Default value: +/- 4g See table 3-8 in the datasheet.

bno055_GYRO_ENABLED = True
bno055_GYRO_GYRO_BANDWIDTH =
# Switch the gyroscope bandwidth and return the new bandwidth. Default value: 32 Hz See table 3-9 in the datasheet.
bno055_GYRO_GYRO_MODE =
# Switch the gyroscope mode and return the new mode. Default value: Normal See table 3-9 in the datasheet.
bno055_GYRO_GYRO_RANGE =
# Switch the gyroscope range and return the new range. Default value: 2000 dps See table 3-9 in the datasheet.

bno055_MAGNET_ENABLED = True
bno055_MAGNET_MAGNET_MODE =
# Switch the magnetometer power mode and return the new mode. Default value: Forced See table 3-10 in the datasheet.
bno055_MAGNET_MAGNET_OPERATION_MODE =
# Switch the magnetometer operation mode and return the new mode. Default value: Regular See table 3-10 in the datasheet.
bno055_MAGNET_MAGNET_RATE =
# Switch the magnetometer data output rate and return the new rate. Default value: 20Hz See table 3-10 in the datasheet.

bno055_TEMPERATURE_ENABLED = True
bno055_EULER_ENABLED = True
bno055_QUATERNION_ENABLED = True
bno055_LINEAR_ACCELEROMETER_ENABLED = True
bno055_GRAVITY_ENABLED = True



PUCKSENSOR:
    # connect over bluetooth internally, no config

