version: "3.9"

services:
  trxusb:
    build:
      context: .
      dockerfile: trxdocker
    container_name: trxusb
    devices:
      - /dev/bus/usb/002  # Update this path to your actual USB device
    group_add:
      - 1001
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
